#!/usr/bin/env node
/**
 * Prisma CLI wrapper that picks the right schema for the database in use.
 *
 *   DATABASE_URL=file:...          -> prisma/schema.prisma           (SQLite, local dev)
 *   DATABASE_URL=postgres(ql)://.. -> prisma/postgres/schema.prisma  (hosted, e.g. Neon)
 *
 * Prisma 5 supports a single provider per schema, and this machine has no local
 * Postgres, so the Postgres schema is DERIVED from the SQLite one (provider swapped)
 * every time this script runs. Never edit prisma/postgres/schema.prisma by hand.
 *
 * Usage:
 *   node scripts/prisma.mjs <any prisma args>      e.g. generate | migrate deploy | studio
 *   node scripts/prisma.mjs pg-init                 write the first Postgres migration (offline)
 *   node scripts/prisma.mjs pg-migration <name>     write a Postgres migration for schema
 *                                                    changes since the last commit (offline)
 */
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

const serverDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
dotenv.config({ path: path.join(serverDir, '.env') });

const SQLITE_SCHEMA = path.join(serverDir, 'prisma', 'schema.prisma');
const PG_DIR = path.join(serverDir, 'prisma', 'postgres');
const PG_SCHEMA = path.join(PG_DIR, 'schema.prisma');
const PG_MIGRATIONS = path.join(PG_DIR, 'migrations');

const url = process.env.DATABASE_URL ?? '';
const isPg = /^postgres(ql)?:\/\//i.test(url);

if (!url && process.env.NODE_ENV === 'production') {
  console.error('[prisma] DATABASE_URL is not set. On Render, paste your Neon connection string into the DATABASE_URL environment variable.');
  process.exit(1);
}

/** Rewrites prisma/postgres/schema.prisma from the SQLite source of truth. */
function derivePostgresSchema() {
  const src = fs.readFileSync(SQLITE_SCHEMA, 'utf8');
  if (!/provider\s*=\s*"sqlite"/.test(src)) {
    throw new Error(`Expected provider = "sqlite" in ${SQLITE_SCHEMA}`);
  }
  const out =
    '// GENERATED from ../schema.prisma by scripts/prisma.mjs — do not edit.\n' +
    src.replace(/provider\s*=\s*"sqlite"/, 'provider = "postgresql"');
  fs.mkdirSync(PG_DIR, { recursive: true });
  const current = fs.existsSync(PG_SCHEMA) ? fs.readFileSync(PG_SCHEMA, 'utf8') : null;
  if (current !== out) fs.writeFileSync(PG_SCHEMA, out);
}

/** Neon suspends idle compute; waking takes longer than Prisma's 5 s default. */
function withConnectTimeout(u) {
  if (!/^postgres(ql)?:\/\//i.test(u) || /[?&]connect_timeout=/.test(u)) return u;
  return `${u}${u.includes('?') ? '&' : '?'}connect_timeout=15`;
}

function runPrisma(args, opts = {}) {
  const require = createRequire(import.meta.url);
  const cli = require.resolve('prisma/build/index.js');
  const result = spawnSync(process.execPath, [cli, ...args], {
    cwd: serverDir,
    stdio: opts.capture ? ['inherit', 'pipe', 'inherit'] : 'inherit',
    env: { ...process.env, DATABASE_URL: withConnectTimeout(url) },
  });
  if (result.status !== 0) process.exit(result.status ?? 1);
  return opts.capture ? result.stdout.toString() : '';
}

function timestamp() {
  return new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
}

function writeMigration(name, sql) {
  if (!sql.trim() || /This is an empty migration/.test(sql)) {
    console.log('[prisma] No schema changes detected for Postgres; nothing written.');
    return;
  }
  const dir = path.join(PG_MIGRATIONS, `${timestamp()}_${name}`);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'migration.sql'), sql);
  fs.writeFileSync(
    path.join(PG_MIGRATIONS, 'migration_lock.toml'),
    '# Please do not edit this file manually\n' +
      '# It should be added in your version-control system (i.e. Git)\n' +
      'provider = "postgresql"\n',
  );
  console.log(`[prisma] Wrote ${path.relative(serverDir, dir)}/migration.sql`);
}

derivePostgresSchema();

const [command, ...rest] = process.argv.slice(2);

if (command === 'pg-init') {
  // `migrate diff` between datamodels needs no database connection.
  const sql = runPrisma(
    ['migrate', 'diff', '--from-empty', '--to-schema-datamodel', PG_SCHEMA, '--script'],
    { capture: true },
  );
  writeMigration('init', sql);
} else if (command === 'pg-migration') {
  const name = rest[0];
  if (!name) {
    console.error('Usage: node scripts/prisma.mjs pg-migration <name>');
    process.exit(1);
  }
  // Compare against the derived schema as of the last commit, so the migration
  // captures exactly what changed in the source schema since then.
  const prev = spawnSync('git', ['show', 'HEAD:server/prisma/postgres/schema.prisma'], {
    cwd: serverDir,
    encoding: 'utf8',
  });
  if (prev.status !== 0) {
    console.error('[prisma] Could not read the committed Postgres schema from git.');
    process.exit(1);
  }
  const tmp = path.join(os.tmpdir(), `lockly-prev-${Date.now()}.prisma`);
  fs.writeFileSync(tmp, prev.stdout);
  try {
    const sql = runPrisma(
      ['migrate', 'diff', '--from-schema-datamodel', tmp, '--to-schema-datamodel', PG_SCHEMA, '--script'],
      { capture: true },
    );
    writeMigration(name, sql);
  } finally {
    fs.rmSync(tmp, { force: true });
  }
} else {
  const args = process.argv.slice(2);
  const hasSchema = args.includes('--schema') || args.some((a) => a.startsWith('--schema='));
  const isDiff = args.includes('diff'); // `migrate diff` has no --schema flag
  const schema = isPg ? PG_SCHEMA : SQLITE_SCHEMA;
  if (!hasSchema && !isDiff) args.push('--schema', schema);
  console.log(`[prisma] using ${path.relative(serverDir, schema)} (${isPg ? 'postgresql' : 'sqlite'})`);
  runPrisma(args);
}
